export enum ERROR_TYPES {
  NAME_OR_PASSWORD_IS_REQUIRED = '用户名或者密码不能为空',
  USER_ALREADY_EXISTS = '用户名已经存在',
  USER_NOT_EXISTS = '用户不存在',
  PASSWORD_IS_INCORRECT = '密码不正确',
  UNAUTHORIZATION = '无效的token',
  UNPERMISSION = '没有权限',
  MENU_NOT_EXISTS = '菜单不存在',
  ADMINISTRATION_CANNOT_BE_DELETED = '管理员不能被删除',
  ADMINISTRATION_CANNOT_BE_MODIFIED = '管理员不能被修改',
  ROLE_ALREADY_EXISTS = '角色名已经存在',
}
